### PR TITLE
fix md syntax error : '\\G' to '\G'

### PR DESCRIPTION
**Pull request by mklzl**
update Deploy.md '\\G' to '\G'

### CODE REVIEW

**Comment by imay** [comment]
@mklzl 
Hi, before you contributing to our project, we need you to sign our CLA.

**Comment by mklzl** [comment]
wait a moment

**Comment by mklzl** [comment]
> @mklzl
> Hi, before you contributing to our project, we need you to sign our CLA.

May I ask what I should do now after SIGNING CLA？

**Comment by imay** [comment]
> > @mklzl
> > Hi, before you contributing to our project, we need you to sign our CLA.
> 
> May I ask what I should do now after SIGNING CLA？

Thanks for your contribution.
I will merge it.

**Review by imay — APPROVED** [review]

**Pull request merged**
